# Site settings
title: eleven-sports
description: >
  Calling all Premier League fans! Eleven Sports has teamed up with luxury travel experts Secret Escapes to give away a five-star stay, every matchweek, until the end of the season. For your chance to win one of 15 getaways, submit your details on the weekly competition entry page below. It's that simple!
baseurl: "/eleven-sports" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]
